### ISSUE TITLE
SSL error with wget

### ISSUE THREAD

**Issue by EvgenIn** [jhoblitt/puppet-selenium#19]
I had an SSL error issue when running the module. 

Maybe should add -     nocheckcertificate => true

**Comment by idleyoungman** [comment]
This is the wget attemped:
```
# wget --no-verbose --output-document='/opt/selenium/jars/selenium-server-standalone-2.42.1.jar' 'https://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.1.jar'
ERROR: certificate common name “*.googleusercontent.com” doesn’t match requested host name “selenium-release.storage.googleapis.com”.
To connect to selenium-release.storage.googleapis.com insecurely, use ‘--no-check-certificate’.
```

**Comment by jhoblitt** [comment]
@idleyoungman I'm planning to merge #19 as soon as there is some test coverage.  Out of curiosity, what version of `wget` is on your system?  I tested with `1.16.1` and did not get an error message, I suspect older versions of wget may not like SAN certs.

**Comment by jhoblitt** [comment]
#27 adds a flag that could be used to work around this problem.
