### ISSUE TITLE
User management toggles

### ISSUE THREAD

**Issue by amswain** [jhoblitt/puppet-selenium#29]
If you don't want the module to manage users or groups, you should have that option.

init.pp

  $manage_user           = true,
  $manage_group         = true,
) inherits selenium::params {
....
  validate_bool($manage_user)
  validate_bool($manage_group)

 if $manage_user {
    user { $user:
      ensure  => present,
      gid     => $group,
    }
  }
  if $manage_group {
    group { $group:
      ensure  => present,
    }
  }

**Comment by jhoblitt** [comment]
@amswain Would you be interested in opening a PR for the feature your requesting?

**Comment by jhoblitt** [comment]
This is resolved by https://github.com/jhoblitt/puppet-selenium/pull/34
