### ISSUE TITLE
rodjek/puppet-logrotate fails with puppet 4 parser and is listed as dependancy in metadata.json

### ISSUE THREAD

**Issue by scarby** [jhoblitt/puppet-selenium#53]
As there now appears to be an issue with rodjek/puppet-logrotate and forge releases are non-existant  would it be possible to move to one of the forks in mededata.json? (one that has a more recent forge release)

**Comment by jhoblitt** [comment]
I've had to work around the same issue in manifests.  Do any of the forks appear to have gained community consensus?

**Comment by davidvanlaatum** [comment]
see https://github.com/rodjek/puppet-logrotate/pull/71

**Comment by jhoblitt** [comment]
@davidvanlaatum That is good news. I would be happy to merge a PR to update the dependencies.

**Comment by jhoblitt** [comment]
I have merged #66, which should resolve this.

**Comment by davidvanlaatum** [comment]
Can we release to the forge

**Comment by jhoblitt** [comment]
A forge release will be made soon.
