### ISSUE TITLE
Puppet approved.

### ISSUE THREAD

**Issue by tphoney** [jhoblitt/puppet-selenium#72]
Hi @jhoblitt ,

I am reaching out to you on behalf of Puppet in regards to your Puppet Approved module jhoblitt/selenium on the Puppet Forge. The Puppet Approved criteria is based on the following tenets; quality composition, reliable operation, and active development. Your module has not been updated on the Puppet Forge for over a year, are there any plans to release a new version of the module? 

There seems to be a few open pull requests that could be merged. If there has not been a new release of the module on the Puppet Forge or a response in the following 3 months, we may have to revoke your Puppet Approved status. If you are not interested in continuing maintenance of the module, you may consider contacting the open source Puppet community Vox Pupuli. They are always interested in adopting modules. There is more information here https://voxpupuli.org/docs/#migrating-a-module-to-voxpupuli.

I look forward to your response, or a new release on the Puppet Forge. 

Regards,
TP Honey
Senior Software Engineer
Puppet Modules Team

PS, i apologise for not getting back on the windows support PR.

**Comment by jhoblitt** [comment]
OK - point well taken ;)
